## Lab 4 task 2 <hr>

## Name: Gerges Tharwat<hr> ID: 41810090

In [33]:
#importing
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#Keras and Tensorflow
import tensorflow.python.keras
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

In [34]:
data = pd.read_csv('autoMPG.csv')
data_CPY = data

In [35]:
data.head(10)

MPG  Cylinders  Displacement  Horsepower  Weight  Acceleration  \
0  18.0          8         307.0       130.0  3504.0          12.0   
1  15.0          8         350.0       165.0  3693.0          11.5   
2  18.0          8         318.0       150.0  3436.0          11.0   
3  16.0          8         304.0       150.0  3433.0          12.0   
4  17.0          8         302.0       140.0  3449.0          10.5   
5  15.0          8         429.0       198.0  4341.0          10.0   
6  14.0          8         454.0       220.0  4354.0           9.0   
7  14.0          8         440.0       215.0  4312.0           8.5   
8  14.0          8         455.0       225.0  4425.0          10.0   
9  15.0          8         390.0       190.0  3850.0           8.5   

   Model Year  Origin                    CarName  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino  
5          70       1           ford galaxie 500  
6          70       1           chevrolet impala  
7          70       1          plymouth fury iii  
8          70       1           pontiac catalina  
9          70       1         amc ambassador dpl

In [36]:
data['Origin'].unique()

array([1, 3, 2])

In [37]:
data['Model Year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [38]:
data.corr()

MPG  Cylinders  Displacement  Horsepower    Weight  \
MPG           1.000000  -0.775396     -0.804203   -0.778427 -0.831741   
Cylinders    -0.775396   1.000000      0.950721    0.842983  0.896017   
Displacement -0.804203   0.950721      1.000000    0.897257  0.932824   
Horsepower   -0.778427   0.842983      0.897257    1.000000  0.864538   
Weight       -0.831741   0.896017      0.932824    0.864538  1.000000   
Acceleration  0.420289  -0.505419     -0.543684   -0.689196 -0.417457   
Model Year    0.579267  -0.348746     -0.370164   -0.416361 -0.306564   
Origin        0.563450  -0.562543     -0.609409   -0.455171 -0.581024   

              Acceleration  Model Year    Origin  
MPG               0.420289    0.579267  0.563450  
Cylinders        -0.505419   -0.348746 -0.562543  
Displacement     -0.543684   -0.370164 -0.609409  
Horsepower       -0.689196   -0.416361 -0.455171  
Weight           -0.417457   -0.306564 -0.581024  
Acceleration      1.000000    0.288137  0.205873  
Model Year        0.288137    1.000000  0.180662  
Origin            0.205873    0.180662  1.000000

In [39]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   MPG           398 non-null    float64
 1   Cylinders     398 non-null    int64  
 2   Displacement  398 non-null    float64
 3   Horsepower    392 non-null    float64
 4   Weight        398 non-null    float64
 5   Acceleration  398 non-null    float64
 6   Model Year    398 non-null    int64  
 7   Origin        398 non-null    int64  
 8   CarName       398 non-null    object 
dtypes: float64(5), int64(3), object(1)
memory usage: 28.1+ KB


In [40]:
data['Horsepower'].fillna(value = data['Horsepower'].mean(), inplace = True)

In [41]:
data = data.drop('CarName', axis = 1)

In [42]:
data.columns

Index(['MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model Year', 'Origin'],
      dtype='object')

In [43]:
sc = StandardScaler()

In [44]:
y = data['MPG']
X = data.drop('MPG', axis = 1)


In [45]:
X.columns

Index(['Cylinders', 'Displacement', 'Horsepower', 'Weight', 'Acceleration',
       'Model Year', 'Origin'],
      dtype='object')

In [46]:
X = pd.DataFrame(sc.fit_transform(X), columns = ['Cylinders', 'Displacement', 'Horsepower', 'Weight', 'Acceleration',
       'Model Year', 'Origin'])
#y = pd.DataFrame(sc.fit_transform(y), columns = ['MPG'])

In [47]:
print(y)
print(X)

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: MPG, Length: 398, dtype: float64
     Cylinders  Displacement  Horsepower    Weight  Acceleration  Model Year  \
0     1.498191      1.090604    0.669196  0.630870     -1.295498   -1.627426   
1     1.498191      1.503514    1.586599  0.854333     -1.477038   -1.627426   
2     1.498191      1.196232    1.193426  0.550470     -1.658577   -1.627426   
3     1.498191      1.061796    1.193426  0.546923     -1.295498   -1.627426   
4     1.498191      1.042591    0.931311  0.565841     -1.840117   -1.627426   
..         ...           ...         ...       ...           ...         ...   
393  -0.856321     -0.513026   -0.484111 -0.213324      0.011586    1.621983   
394  -0.856321     -0.925936   -1.375302 -0.993671      3.279296    1.621983   
395  -0.856321     -0.561039   -0.536534 -0.798585     -1.440730    1.621983   
396  -0.856321     -0.705077 

In [48]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [49]:
print(X_train)
print(y_train)

     Cylinders  Displacement  Horsepower    Weight  Acceleration  Model Year  \
56   -0.856321     -0.983552   -0.903495 -1.200582      1.790672   -1.356642   
256   0.320935      0.303193   -0.117149  0.543376      0.592512    0.538847   
60   -0.856321     -0.513026   -0.379265 -0.664980      1.427593   -1.085858   
306   0.320935     -0.196141    0.276023 -0.443881     -1.549654    0.809631   
373  -0.856321     -0.513026   -0.326842 -0.124648      0.302049    1.621983   
..         ...           ...         ...       ...           ...         ...   
42    1.498191      1.820399    1.979772  2.346452     -1.477038   -1.356642   
361   0.320935     -0.244154    0.302235 -0.083266     -1.077651    1.351199   
295  -0.856321     -0.916334   -0.641380 -1.247875     -0.424109    0.809631   
258   0.320935      0.360808    0.013908  0.484259      0.084201    0.538847   
244  -0.856321     -0.993154   -1.480148 -1.165111      2.153751    0.538847   

       Origin  
56  -0.715145  
256 -0.

In [50]:
X.isna().any()

Cylinders       False
Displacement    False
Horsepower      False
Weight          False
Acceleration    False
Model Year      False
Origin          False
dtype: bool

In [51]:
model = Sequential()

In [52]:
model.add(Dense(10, input_dim = 7, activation = 'relu'))
model.add(Dense(5, activation = 'relu'))
model.add(Dense(1))

In [53]:
model.compile(loss = 'mean_squared_error', optimizer = 'adam')

In [61]:
history = model.fit(X_train, y_train, epochs = 500, batch_size = 64)

Epoch 1/500
5/5 [==============================] - 0s 2ms/step - loss: 6.8702
Epoch 2/500
5/5 [==============================] - 0s 5ms/step - loss: 6.8773
Epoch 3/500
5/5 [==============================] - 0s 5ms/step - loss: 6.8646
Epoch 4/500
5/5 [==============================] - 0s 4ms/step - loss: 6.8617
Epoch 5/500
5/5 [==============================] - 0s 3ms/step - loss: 6.8630
Epoch 6/500
5/5 [==============================] - 0s 5ms/step - loss: 6.8582
Epoch 7/500
5/5 [==============================] - 0s 4ms/step - loss: 6.8531
Epoch 8/500
5/5 [==============================] - 0s 5ms/step - loss: 6.8482
Epoch 9/500
5/5 [==============================] - 0s 6ms/step - loss: 6.8450
Epoch 10/500
5/5 [==============================] - 0s 5ms/step - loss: 6.8413
Epoch 11/500
5/5 [==============================] - 0s 5ms/step - loss: 6.8415
Epoch 12/500
5/5 [==============================] - 0s 5ms/step - loss: 6.8382
Epoch 13/500
5/5 [==============================] - 0s 4ms/st

5/5 [==============================] - 0s 5ms/step - loss: 6.6285
Epoch 105/500
5/5 [==============================] - 0s 5ms/step - loss: 6.6261
Epoch 106/500
5/5 [==============================] - 0s 6ms/step - loss: 6.6296
Epoch 107/500
5/5 [==============================] - 0s 3ms/step - loss: 6.6247
Epoch 108/500
5/5 [==============================] - 0s 5ms/step - loss: 6.6232
Epoch 109/500
5/5 [==============================] - 0s 4ms/step - loss: 6.6251
Epoch 110/500
5/5 [==============================] - 0s 3ms/step - loss: 6.6203
Epoch 111/500
5/5 [==============================] - 0s 4ms/step - loss: 6.6228
Epoch 112/500
5/5 [==============================] - 0s 4ms/step - loss: 6.6210
Epoch 113/500
5/5 [==============================] - 0s 4ms/step - loss: 6.6205
Epoch 114/500
5/5 [==============================] - 0s 4ms/step - loss: 6.6150
Epoch 115/500
5/5 [==============================] - 0s 4ms/step - loss: 6.6106
Epoch 116/500
5/5 [==============================] - 0

5/5 [==============================] - 0s 4ms/step - loss: 6.4982
Epoch 207/500
5/5 [==============================] - 0s 4ms/step - loss: 6.4949
Epoch 208/500
5/5 [==============================] - 0s 4ms/step - loss: 6.5024
Epoch 209/500
5/5 [==============================] - 0s 4ms/step - loss: 6.5045
Epoch 210/500
5/5 [==============================] - 0s 4ms/step - loss: 6.5153
Epoch 211/500
5/5 [==============================] - 0s 4ms/step - loss: 6.4876
Epoch 212/500
5/5 [==============================] - 0s 4ms/step - loss: 6.4964
Epoch 213/500
5/5 [==============================] - 0s 4ms/step - loss: 6.4984
Epoch 214/500
5/5 [==============================] - 0s 4ms/step - loss: 6.4933
Epoch 215/500
5/5 [==============================] - 0s 4ms/step - loss: 6.4861
Epoch 216/500
5/5 [==============================] - 0s 5ms/step - loss: 6.4859
Epoch 217/500
5/5 [==============================] - 0s 4ms/step - loss: 6.4875
Epoch 218/500
5/5 [==============================] - 0

5/5 [==============================] - 0s 4ms/step - loss: 6.3827
Epoch 309/500
5/5 [==============================] - 0s 5ms/step - loss: 6.3769
Epoch 310/500
5/5 [==============================] - 0s 5ms/step - loss: 6.3781
Epoch 311/500
5/5 [==============================] - 0s 4ms/step - loss: 6.3760
Epoch 312/500
5/5 [==============================] - 0s 4ms/step - loss: 6.3750
Epoch 313/500
5/5 [==============================] - 0s 4ms/step - loss: 6.3773
Epoch 314/500
5/5 [==============================] - 0s 4ms/step - loss: 6.3706
Epoch 315/500
5/5 [==============================] - 0s 5ms/step - loss: 6.3765
Epoch 316/500
5/5 [==============================] - 0s 3ms/step - loss: 6.3751
Epoch 317/500
5/5 [==============================] - 0s 3ms/step - loss: 6.3721
Epoch 318/500
5/5 [==============================] - 0s 4ms/step - loss: 6.3736
Epoch 319/500
5/5 [==============================] - 0s 5ms/step - loss: 6.3685
Epoch 320/500
5/5 [==============================] - 0

5/5 [==============================] - 0s 4ms/step - loss: 6.2664
Epoch 411/500
5/5 [==============================] - 0s 3ms/step - loss: 6.2673
Epoch 412/500
5/5 [==============================] - 0s 4ms/step - loss: 6.2686
Epoch 413/500
5/5 [==============================] - 0s 5ms/step - loss: 6.2621
Epoch 414/500
5/5 [==============================] - 0s 3ms/step - loss: 6.2693
Epoch 415/500
5/5 [==============================] - 0s 4ms/step - loss: 6.2595
Epoch 416/500
5/5 [==============================] - 0s 4ms/step - loss: 6.2602
Epoch 417/500
5/5 [==============================] - 0s 5ms/step - loss: 6.2572
Epoch 418/500
5/5 [==============================] - 0s 5ms/step - loss: 6.2572
Epoch 419/500
5/5 [==============================] - 0s 3ms/step - loss: 6.2593
Epoch 420/500
5/5 [==============================] - 0s 3ms/step - loss: 6.2541
Epoch 421/500
5/5 [==============================] - 0s 4ms/step - loss: 6.2656
Epoch 422/500
5/5 [==============================] - 0

In [62]:
y_pred = model.predict(X_test)

In [63]:
y_test

14     24.0
340    25.8
294    34.1
11     14.0
316    19.1
       ... 
358    31.6
101    23.0
330    40.9
74     13.0
129    31.0
Name: MPG, Length: 80, dtype: float64

In [64]:
y_pred

array([[24.576063],
       [27.399527],
       [35.407185],
       [17.649197],
       [22.003618],
       [17.042788],
       [18.470158],
       [31.481531],
       [34.303825],
       [20.139473],
       [19.402418],
       [22.664816],
       [32.54693 ],
       [32.756386],
       [34.164494],
       [23.862581],
       [17.24655 ],
       [22.920767],
       [19.933455],
       [19.498272],
       [23.345167],
       [25.145824],
       [21.467678],
       [15.548586],
       [14.997845],
       [30.026861],
       [20.539053],
       [17.619987],
       [30.508444],
       [16.0106  ],
       [16.455528],
       [17.661493],
       [17.354296],
       [17.222452],
       [29.26602 ],
       [19.079489],
       [34.49216 ],
       [30.669193],
       [17.66798 ],
       [26.809776],
       [23.813957],
       [19.57595 ],
       [21.060621],
       [24.881567],
       [29.39393 ],
       [26.332663],
       [16.931229],
       [18.18974 ],
       [17.602942],
       [24.510542],


In [58]:
model.save('task2_model_loss_6.h5')

In [65]:
from sklearn.metrics import mean_squared_error

In [66]:
print("RMSE",np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE 3.1873324771154614
